// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/postRepoInterface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "localEyes/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPostRepository is a mock of PostRepository interface.
type MockPostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPostRepositoryMockRecorder
}

// MockPostRepositoryMockRecorder is the mock recorder for MockPostRepository.
type MockPostRepositoryMockRecorder struct {
	mock *MockPostRepository
}

// NewMockPostRepository creates a new mock instance.
func NewMockPostRepository(ctrl *gomock.Controller) *MockPostRepository {
	mock := &MockPostRepository{ctrl: ctrl}
	mock.recorder = &MockPostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostRepository) EXPECT() *MockPostRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPostRepository) Create(post *models.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", post)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPostRepositoryMockRecorder) Create(post interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPostRepository)(nil).Create), post)
}

// DeleteByPId mocks base method.
func (m *MockPostRepository) DeleteByPId(PId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByPId", PId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByPId indicates an expected call of DeleteByPId.
func (mr *MockPostRepositoryMockRecorder) DeleteByPId(PId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByPId", reflect.TypeOf((*MockPostRepository)(nil).DeleteByPId), PId)
}

// DeleteByUId mocks base method.
func (m *MockPostRepository) DeleteByUId(UId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUId", UId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUId indicates an expected call of DeleteByUId.
func (mr *MockPostRepositoryMockRecorder) DeleteByUId(UId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUId", reflect.TypeOf((*MockPostRepository)(nil).DeleteByUId), UId)
}

// DeleteByUIdPId mocks base method.
func (m *MockPostRepository) DeleteByUIdPId(UId, PId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUIdPId", UId, PId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUIdPId indicates an expected call of DeleteByUIdPId.
func (mr *MockPostRepositoryMockRecorder) DeleteByUIdPId(UId, PId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUIdPId", reflect.TypeOf((*MockPostRepository)(nil).DeleteByUIdPId), UId, PId)
}

// GetAllPosts mocks base method.
func (m *MockPostRepository) GetAllPosts() ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPosts")
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPosts indicates an expected call of GetAllPosts.
func (mr *MockPostRepositoryMockRecorder) GetAllPosts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPosts", reflect.TypeOf((*MockPostRepository)(nil).GetAllPosts))
}

// GetPostsByFilter mocks base method.
func (m *MockPostRepository) GetPostsByFilter(filter string) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsByFilter", filter)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsByFilter indicates an expected call of GetPostsByFilter.
func (mr *MockPostRepositoryMockRecorder) GetPostsByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsByFilter", reflect.TypeOf((*MockPostRepository)(nil).GetPostsByFilter), filter)
}

// GetPostsByPId mocks base method.
func (m *MockPostRepository) GetPostsByPId(PId int) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsByPId", PId)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsByPId indicates an expected call of GetPostsByPId.
func (mr *MockPostRepositoryMockRecorder) GetPostsByPId(PId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsByPId", reflect.TypeOf((*MockPostRepository)(nil).GetPostsByPId), PId)
}

// GetPostsByUId mocks base method.
func (m *MockPostRepository) GetPostsByUId(UId int) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsByUId", UId)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsByUId indicates an expected call of GetPostsByUId.
func (mr *MockPostRepositoryMockRecorder) GetPostsByUId(UId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsByUId", reflect.TypeOf((*MockPostRepository)(nil).GetPostsByUId), UId)
}

// UpdateLike mocks base method.
func (m *MockPostRepository) UpdateLike(PId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLike", PId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLike indicates an expected call of UpdateLike.
func (mr *MockPostRepositoryMockRecorder) UpdateLike(PId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLike", reflect.TypeOf((*MockPostRepository)(nil).UpdateLike), PId)
}

// UpdateUserPost mocks base method.
func (m *MockPostRepository) UpdateUserPost(PId, UId int, title, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPost", PId, UId, title, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPost indicates an expected call of UpdateUserPost.
func (mr *MockPostRepositoryMockRecorder) UpdateUserPost(PId, UId, title, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPost", reflect.TypeOf((*MockPostRepository)(nil).UpdateUserPost), PId, UId, title, content)
}
